image: Ubuntu

services:
  - docker

stack: jdk 11

branches:
  only:
    - main

build: off

install:
  - sudo docker-compose up -d
  - sleep 10
  - java -Dspring.datasource.url=jdbc:mysql://localhost:3306/app -jar ./artifacts/aqa-shop.jar &

build_script:
  - sleep 10
  - sudo chmod +x gradlew
  - ./gradlew test -Dselenide.headless=true -Ddb.url=jdbc:mysql://localhost:3306/app --info