image: Ubuntu  # образ для сборки

services:
  - docker

stack: jdk 11  # версия JDK

branches:
  only:
    - main  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  # запускаем SUT (& означает, что в фоновом режиме не блокируем терминал для запуска тестов)
#  - ps: sudo curl -L "https://github.com/docker/compose/releases/download/1.26.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
#  - ps: sudo chmod +x /usr/local/bin/docker-compose
  - ps: sudo docker-compose up -d
  - sleep 10
  - java -jar ./artifacts/aqa-shop.jar &

build_script:
  - sleep 10
  - sudo chmod +x gradlew
  - ./gradlew test -Dselenide.headless=true --info