image: Visual Studio 2017  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - main  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  # запускаем SUT (& означает, что в фоновом режиме не блокируем терминал для запуска тестов)
  - docker version
  - cd "C:\Program Files\Docker\Docker"
  - DockerCli.exe -SwitchDaemon
  - docker pull node:slim
  - docker pull mysql:slim
  - choco install docker-compose
  - docker-compose up
  - java -jar ./artifacts/aqa-shop.jar &

build_script:
  - chmod +x gradlew
  - ./gradlew test -Dselenide.headless=true --info