image: Visual Studio 2017  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - main  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  # запускаем SUT (& означает, что в фоновом режиме не блокируем терминал для запуска тестов)
  - docker version
  - choco install docker-compose
  - $FILE = "C:\ProgramData\Docker\config\daemon.json"
  - (Get-Content -Path $FILE) -replace '"experimental":false','"experimental":true' | Set-Content -Path $FILE
  - PS C:\WINDOWS\system32> Restart-Service docker
  - docker-compose build
  - docker-compose up
  - java -jar ./artifacts/aqa-shop.jar &

build_script:
  - chmod +x gradlew
  - ./gradlew test -Dselenide.headless=true --info