version: 1.0.{build}
image: Visual Studio 2017  # образ для сборки
platform:
  # будем гонять CI на amd64 и x86...
  - x64
  - x86

stack: jdk 11  # версия JDK

branches:
  only:
    - main  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  # запускаем SUT (& означает, что в фоновом режиме не блокируем терминал для запуска тестов)
  - docker version
  - docker-compose up
  - java -jar ./artifacts/aqa-shop.jar &

build_script:
  - chmod +x gradlew
  - ./gradlew test -Dselenide.headless=true --info