image: Visual Studio 2019  # образ для сборки

services:
  - mysql
  - postgresql

stack: jdk 11  # версия JDK

branches:
  only:
    - main  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  # запускаем SUT (& означает, что в фоновом режиме не блокируем терминал для запуска тестов)
#  - cd gate-simulator
#  - npm install
#  - npm start &
  - dir C:\
  - java -jar ./artifacts/aqa-shop.jar &

build_script:
  - chmod +x gradlew
  - ./gradlew test -Dselenide.headless=true --info