version: '3.3'

services:

  nodejs:
    build: .
    ports:
      - "9999:9999"

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
      - MYSQL_RANDOM_ROOT_PASSWORD=yes

#networks:
#  default:
#    external:
#      name: none

#  postgresql:
#    image: postgres:latest
#    ports:
#      - "5432:5432"
#    environment:
#      - POSTGRES_DB=app
#      - POSTGRES_USER=PUBLIC
#      - POSTGRES_PASSWORD=pass