version: '3.3'

services:

  nodejs:
    build: .
    ports:
      - "9999:9999"

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
      - MYSQL_RANDOM_ROOT_PASSWORD=yes

  postgresql:
    image: postgres:latest
    volumes:
      - ./pgdata:/var/lib/postgresql/pgdata
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=app
      - POSTGRES_DB=app

#networks:
#  default:
#    external:
#      name: nat